Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"
  config.vm.provider :virtualbox do |v|
    v.gui = true
    v.memory = 2048
  end
  config.vm.provision :shell, inline: "cd /etc/yum.repos.d/"
  config.vm.provision :shell, inline: "sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*"
  config.vm.provision :shell, inline: "sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*"
  config.vm.provision :shell, inline: "yum update -y"
  config.vm.provision :shell, inline: "yum install httpd -y"
  config.vm.provision :shell, inline: "yum install php -y"
  config.vm.provision :shell, inline: "yum install mariadb-server mariadb -y"
  config.vm.provision :shell, inline: "systemctl start mariadb"
  config.vm.provision :shell, inline: "systemctl enable mariadb.service"
  config.vm.provision :shell, inline: "systemctl start httpd.service "
  config.vm.provision :shell, inline: "systemctl enable httpd.service"

end