Vagrant.configure("2") do |config|
  config.vm.box = "romych/cent7web"
  config.vm.box_version = "1"
  config.vm.provider :virtualbox do |v|
    v.gui = true
    v.memory = 2048
  end
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 80, host: 8081
  config.vm.provision :shell, inline: "yum install git -y"
  config.vm.provision :shell, inline: "mkdir -p /var/www/8080"
  config.vm.provision :shell, inline: "git clone https://github.com/Fenikks/itacademy-devops-files /tmp/itacademy"
  config.vm.provision :shell, inline: "cp /tmp/itacademy/01-demosite-static/index.html /var/www/8080/index.html"
  config.vm.provision :shell, inline: "cp /tmp/itacademy/01-demosite-php/index.php /var/www/html/index.php"
  config.vm.provision :shell, inline: "rm -rf /tmp/itacademy"
  config.vm.provision :shell, inline: 'cat << EOF >> /etc/httpd/conf/httpd.conf
Listen 8080
<VirtualHost *:8080>
  DocumentRoot "/var/www/8080/"
</VirtualHost>
EOF
'
  config.vm.provision :shell, inline: "systemctl restart httpd.service"

end

