Vagrant.configure("2") do |config|
  config.vm.box = "romych/cent7web"
  config.vm.box_version = "1"
  config.vm.provider :virtualbox do |v|
    v.gui = false
    v.memory = 2048
  end

  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 80, host: 8081
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yaml"
  end

end

