Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian10"
    config.vm.synced_folder "./jenkins", "/vagrant"
    config.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus   = 1     
    end  
    config.vm.hostname = "jenkins.vm"
    config.vm.network "private_network", ip: "192.168.56.10"
    config.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "/vagrant/playbook.yaml"
        ansible.become = true
        ansible.inventory_path = "/vagrant/hosts"
        ansible.limit = 'all'
        ansible.galaxy_role_file = "/vagrant/requirements.yml"
    end


end
