Vagrant.configure("2") do |config|
    config.vm.box = "generic/centos8"
    config.vm.synced_folder ".", "/vagrant"
    config.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus   = 1     
    end  
    config.vm.provision "shell", inline: "yum install -y https://yum.puppet.com/puppet7-release-el-8.noarch.rpm"
    config.vm.provision "shell", inline: "sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config"
    config.vm.provision "shell", inline: "systemctl restart sshd.service"
    config.vm.provision "shell", inline: "systemctl stop firewalld"
    config.vm.provision "shell", inline: "systemctl disable firewalld"


    
    config.vm.define "slave1.puppet" do |slave1|
        slave1.vm.hostname = "slave1.puppet"   
        slave1.vm.network "private_network", ip: "192.168.50.10"
        slave1.vm.network "forwarded_port", guest: 80, host: 8080
    end
  
    config.vm.define "slave2.puppet" do |slave2|
        slave2.vm.hostname = "slave2.puppet"
        slave2.vm.network "private_network", ip: "192.168.50.11"
        slave2.vm.network "forwarded_port", guest: 80, host: 8081      
    end   
    
    config.vm.define "master.puppet" do |master|
        master.vm.hostname = "master.puppet"
        master.vm.network "private_network", ip: "192.168.50.5"
        master.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "playbook.yaml"
            ansible.become = true
            ansible.inventory_path = "inventory/hosts"
            ansible.limit = 'all'
        end
    end

  end 