- hosts: jenkins.vm
  become: true
  
  vars:
    jenkins_hostname: "192.168.56.10"
    java_packages:
      - openjdk-11-jdk

  roles:
    - role: geerlingguy.java

    - role: geerlingguy.jenkins
      jenkins_plugins_install_dependencies: true
      jenkins_plugins:
        - name: golang
          version: latest
          with_dependencies: yes
        - name: git
          version: latest
          with_dependencies: yes
        - name: github
          version: latest
          with_dependencies: yes
        - name: okhttp-api
          version: latest
          with_dependencies: yes
        - name: display-url-api
          version: latest
          with_dependencies: yes
        - name: credentials
          version: latest
          with_dependencies: yes
        - name: structs
          version: latest
          with_dependencies: yes
        - name: workflow-scm-step
          version: latest
          with_dependencies: yes
        - name: scm-api
          version: latest
          with_dependencies: yes
        - name: mailer
          version: latest
          with_dependencies: yes
        - name: git-client
          version: latest
          with_dependencies: yes
        - name: script-security
          version: latest
          with_dependencies: yes
        - name: workflow-step-api
          version: latest
          with_dependencies: yes
        - name: credentials-binding
          version: latest
          with_dependencies: yes
        - name: ssh-credentials
          version: latest
          with_dependencies: yes
        - name: plain-credentials
          version: latest
          with_dependencies: yes
        - name: trilead-api
          version: latest
          with_dependencies: yes
        - name: apache-httpcomponents-client-4-api
          version: latest
          with_dependencies: yes
        - name: jsch
          version: latest
          with_dependencies: yes
        - name: caffeine-api
          version: latest
          with_dependencies: yes
        - name: jakarta-activation-api
          version: latest
          with_dependencies: yes
        - name: instance-identity
          version: latest
          with_dependencies: yes
        - name: jakarta-mail-api
          version: latest
          with_dependencies: yes
        - name: token-macro
          version: latest
          with_dependencies: yes
        - name: jackson2-api
          version: latest
          with_dependencies: yes
        - name: github-api
          version: latest
          with_dependencies: yes
        - name: jaxb
          version: latest
          with_dependencies: yes
        - name: snakeyaml-api
          version: latest
          with_dependencies: yes
        - name: javax-activation-api
          version: latest
          with_dependencies: yes
        - name: jaxb
          version: latest
          with_dependencies: yes
        - name: ant
          version: latest
          with_dependencies: yes
        - name: bootstrap5-api
          version: 5.2.0-1
          with_dependencies: yes
        - name: build-timeout
          version: latest
          with_dependencies: yes
        - name: javax-mail-api
          version: latest
          with_dependencies: yes
        - name: sshd
          version: latest
          with_dependencies: yes
        - name: bouncycastle-api
          version: latest
          with_dependencies: yes
        - name: instance-identity
          version: latest
          with_dependencies: yes
        - name: mina-sshd-api-common
          version: latest
          with_dependencies: yes
        - name: bouncycastle-api
          version: latest
          with_dependencies: yes
        - name: mina-sshd-api-core
          version: latest
          with_dependencies: yes
        - name: plugin-util-api
          version: latest
          with_dependencies: yes
        - name: workflow-support
          version: 838.va_3a_087b_4055b
          with_dependencies: yes
        - name: workflow-api
          version: 1164.v760c223ddb_32
          with_dependencies: yes
        - name: checks-api
          version: 1.7.5
          with_dependencies: yes
        - name: popper2-api
          version: 2.11.5-2
          with_dependencies: yes
        - name: font-awesome-api
          version: 6.1.1-1
          with_dependencies: yes

  tasks:
    - name: install python-pip
      apt:
        name: python-pip
        state: present

    - name: Install python-jenkins
      pip:
        name: python-jenkins

    - name: Install libxml
      pip:
        name: lxml

    - name: add job gobuild
      jenkins_job:
        config: "{{ lookup('file', '/vagrant/gobuild_job.xml') }}"
        name: g0build
        password: admin
        url: http://localhost:8080
        user: admin

    # - name: configuration go 1.16
    #   copy:
    #     src: /vagrant/tools/
    #     dest: /var/lib/jenkins/tools/
    #     owner: vagrant
    #     group: vagrant
    #     mode: '0755'

    - name: restart jenkins
      service: name=jenkins state=restarted

    - name: Wait for Jenkins to restart
      wait_for: host=localhost port=8080 delay=20 timeout=300