Vagrant.configure("2") do |config|
    config.vm.box = "debian/buster64"
    config.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1"
    config.vm.network "forwarded_port", guest: 8081, host: 8081, host_ip: "127.0.0.1"
    config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.name   = "lxc2.vagrant.vm"
    end
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yaml"
      end
end
